theme: jekyll-theme-leap-day
title: Welcome to the Simpsons script generator!
description:  You can create your own original Simpsons scripts based on the past scripts that you train the network on.
![Simpsons jpg]({{ https://nyck33.github.io/Simpsons-script-generator }}/simpsons-season-29-grampy-can-ya-hear-me.jpg)
