theme: jekyll-theme-leap-day
title: Welcome to the Simpsons script generator!
description:  You can create your own original Simpsons scripts based on the past scripts that you train the network on.
<img src="https://www.google.com/url?sa=i&source=images&cd=&cad=rja&uact=8&ved=2ahUKEwiF3cGMp_HfAhWnJDQIHajMB0EQjRx6BAgBEAU&url=https%3A%2F%2Fwww.denofgeek.com%2Fus%2Ftv%2Fthe-simpsons%2F274565%2F
the-simpsons-season-30-release-date-and-episode-details&psig=AOvVaw1ClUcirBo_h7Vq9al3S09F&ust=1547693859642019" alt="hi" 
class="inline"/>
